### ISSUE TITLE
Embed JS is broken

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#102]
I tried to embed a JS publication list in a test site (http://dev.adw-goe.de/index.php?id=681).

Only the Bielefeld code work. Either our Göttingen nor the demo.librecat code work. 

I get the error 

> publication?q=type%3Dbook_chapter&ftyp=js:19 Uncaught SyntaxError: Invalid or unexpected token

<img width="1636" alt="bildschirmfoto 2016-12-02 um 09 48 45" src="https://cloud.githubusercontent.com/assets/4047340/20827828/8f2b4068-b874-11e6-83ba-835fea86c746.png">

**Comment by petrakohorst** [comment]
This happens, when there is a line break within the document.write call. In your tt-template: remove the line break behind the html comment (and any other line breaks) and it'll work.

This is a recurring problem for us, too. js-templates for this kind of embedding need to consist of one single line. Otherwise the embedding will break. Even if there is a newline after that one line, it will break. My atom editor automatically adds a newline at the end of every file when saving it and if I forget about that and upload it unchecked, it breaks our js embeddings, too.

**Comment by nilswindisch** [comment]
thank you for your quick reply, can you specify the tt-file?

**Comment by petrakohorst** [comment]
Template is called citation.tt. That's the one that's being used there. If you change it to contain only one line, it'll work.
Maybe delete the html comment altogether and merge the remaining lines into one.

**Comment by nilswindisch** [comment]
this one: https://github.com/LibreCat/LibreCat/blob/master/views/citation.tt ?
I'm afraid/suspect the HTML is set within data from the database an not the code.

**Comment by vpeil** [comment]
please check if it works for you, see the related commit.

**Comment by petrakohorst** [comment]
@dbeucke  The embed url would then be `/embed?q=type=book_chapter&fmt=js`

**Comment by nilswindisch** [comment]
judging from the amount of code commited this looks like more than a simple fix. Thank you. Will have a look asap (maybe not this week though)
