### ISSUE TITLE
What is/does /scss/bielestrap.scss?

### ISSUE THREAD

**Issue by nilswindisch** [LibreCat/LibreCat#129]

**Comment by nilswindisch** [comment]
seems to be necessary to get the familiar look.

**Comment by nilswindisch** [comment]
propose to call it "librecat" instead of "biele", cause biele sounds tied to Bielefeld.

**Comment by verheyenkoen** [comment]
This appears to be a [customized](https://getbootstrap.com/docs/3.3/customize/) Bootstrap 3.3.5 CSS file (not SASS/SCSS). I unminified and diffed it against the original 3.3.5 release and it's not exactly the same (I didn't check the whole diff), however it's hard to believe anyone would have made any meaningful manual changes to it (since it's minified). Also there's no git history for the file. 

The idea of getting a customized Bootstrap dist is when you know you're not gonna use certain Bootstrap components. So basically save some time in loading/rendering. Maybe @nics remembers  why he needed it. It was only committed a year ago.

**Comment by vpeil** [comment]
Could this file be an explaination for that? Looks like a customized bootstrap config

https://github.com/LibreCat/LibreCat/blob/master/public/config.json

**Comment by verheyenkoen** [comment]
Probably yes.

**Comment by nics** [comment]
I don’t think i introduced the file, i just renamed it

**Comment by vpeil** [comment]
@verheyenkoen fixed this with f6bcc1e
