### ISSUE TITLE
Migrate to Bootstrap 4

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#136]
https://v4-alpha.getbootstrap.com/

**Comment by vpeil** [comment]
There is a stable release now: https://getbootstrap.com/

@verheyenkoen do you think, this transition can be made smoothly?

**Comment by verheyenkoen** [comment]
Will be quite a job I guess. Some class names have changed. Others have been dropped while others have been introduced. We will have to go through all the templates I guess. I think the best approach is to make sure this can be done in the shortest possible timespan, because we'll definitely need to branch for this and the longer that takes, the more merge conflicts we'll have to resolve.

I found a [site](http://upgrade-bootstrap.bootply.com/) with a kind-of cheatsheet and converter tool but since our templates are not pure HTML, the converter tool will probably not be an option.

**Comment by vpeil** [comment]
that seems quite a lot of "search and replace" actions
