### ISSUE TITLE
When adding a new file to the dropzone the locale message isn't displayed

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#167]
Existing files in the record show an access_level like 'Open Access'. When you drop in a new file it displays 'open_access'.

**Comment by vpeil** [comment]
Yes, the problem is that language string are replaced/generated at template processing time.
If you drop a new file a JS function inserts content into the form with the language variable instead with their values. I don't know how to solve this one. Have to reconsider the whole thing is way too complicated.
