### ISSUE TITLE
RTF export is empty

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#219]

**Comment by vpeil** [comment]
that is due to our change with the default citation style (Title + "short")....

**Comment by nicolasfranck** [comment]
It's still empty in the current dev branch.

I noticed a unused method in Catmandu::Exporter::RTF: _add_cite.
That method is never called because it's overridden by the method with
the same name of Catmandu::Exporter::Cite ( put some log statements
inside these methods too see this!).

Reason: "extends" is called AFTER all perl methods are compiled, so _add_cite of the
child class is seen first, then _add_cite of the parent class.
Methods should be overridden with "around", so Moo can follow.

**Comment by vpeil** [comment]
fixed by PR #325
