### ISSUE TITLE
Template error on year facet

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#267]
When the year file in the YAML data is defined as an integer:

```(yaml)
   year: 2009
```
it crashed the `views/facets/year.tt` with a `Core::Template` error:

```(json)
{
  "exception": "Core::Template",
  "error": "core - template - date error - bad time/date string:  expects 'h:m:s d:m:y'  got: '2.009' at /opt/librecat/local/lib/perl5/Dancer/Template/Abstract.pm line 91.\n"
}
```

This doesn't happen when the year field is a string field:

```(yaml)
 year: "2009"
```

Weird?!

**Comment by christianmahnke** [comment]
The current fix should be considered a ugly hack, since it adds data type handling logic to the view layer (in a architectural sense), see [4fe1b04f1906addf8f04698efbc3930a556e13b1](https://github.com/LibreCat/LibreCat/commit/4fe1b04f1906addf8f04698efbc3930a556e13b1). A real fix would be to solve [#250](https://github.com/LibreCat/LibreCat/issues/250).

**Comment by phochste** [comment]
@christianmahnke This has nothing to do with validation nor #250. But indeed it is an ugly hack to find out why ElasticSearch behaves the way it does

**Comment by christianmahnke** [comment]
Well, at least if one is arguing on top of the current schema you might be right. But if the code could guarantee, that the ingest won't permit violations of the schema, this wouldn't have happened. You could have fixed this by forcing the year to a certain type in the schema. From my point of view #250 is major design flaw that hit us very hard...

Why ElesticSearch behave this way should be clear, parts of the code tells ElasticSearch to do this...

**Comment by phochste** [comment]
@christianmahnke Well if you know the answer why dont you put a pull request Christian

**Comment by vpeil** [comment]
To me the answer is not obvious, too.

**Comment by christianmahnke** [comment]
I won't since it requires changes to the architecture, and I'm not a Perl developer. You don't seem to understand the maening of a data type and that's probably related to the fact that think in Perl. In Perl there are scalars which are basically strings and integers. Thats not how ElasticSearch or even YAML works, there are differences between those two types.
Consider the following snippet:
```
bla: 1
blub: '1'
```
Thats not the same in YAML, the first ist the integer `1`, the second is the string `1`. ElasticSearch treats those different, YAML to. The LibreCat permits both as a Year. And that's the reason, why sometimes the wrong thing ends up in ElasticSearch. If there would be a layer on top of the storage system that does the validation always, than this couldn't be triggered if you jus change the schema. Do you know what I mean?

**Comment by phochste** [comment]
I know perfectly what you mean (i happen to think in  Perl, C, Java, Clojure and a hell a lot of programming languages I'm willing to contribute to).

This issue this will not be solved with validation, which doesn't do type conversion.  I would you like to contribute positively to this project and not judge the programmers who are creating solutions to this project and are willing to spend a lot of their valuable time to help the Göttingen installation with there issues.

**Comment by christianmahnke** [comment]
Well, I'm not saying validation alone will solve this, but please see it in the right context, which would be #249, which you closed without even commenting it (which is a bad habit anyways). I'm saying if you want to be this liberal you can expect to break things. 

My proposal would be: Don't be this liberal regarding the schema, since it leads to many many problems and gets you nothing. Get the architecture straight on this, which is always validate. If that had been in place neither #245 nor #246 or #252 would have ever happened. They are all related to each other.

I wonder why these quite simple things don't show up in the other installations.
