### ISSUE TITLE
Documenting the schema

### ISSUE THREAD

**Issue by pkiraly** [LibreCat/LibreCat#28]
I have started writing a data schema documentation, see [Data Schema](https://github.com/LibreCat/LibreCat/wiki/Data-schema). I try to figure out the meaning of the fields. Could you please check it whether the intented usage is in sync what I have recorded, and fill the gaps I was not able to figure out?

**Comment by phochste** [comment]
This is all based on the JSON schema which, I think, only contains the mandatory fields and not the optional fields. Might need to add a column to indicate which fields are mandatory and add later the optional fields (e.g. file: for publication).

**Comment by pkiraly** [comment]
Are the mandatory filds noted such as `required: ["_id","rec_type","title"]`?

**Comment by phochste** [comment]
Yes, catmandu.forms.yml contains all the field in the forms. It is an exercise to check if all the possible fields are really in the catmandu.schema.yml (as should be).

**Comment by pkiraly** [comment]
An inconsistency: researcher's external_id.isi has a constraints ("^[0-9]+$"), while isi doesn't have.

**Comment by pkiraly** [comment]
It seems the catmandu.forms.yml and catmandu.schema.yml are quite inconsistent. Maybe I misinterpret it. Some examples taken from the publication_types.book.fields:

* forms: alternative_title, schema: alternativeTitle
* forms: place, schema: NA
* forms: edition, schema: NA
* forms: project, schema: publication doesn't refer to schema
* forms: research_group, schema: publication doesn't refer to research_group
* forms: year_extern, schema: year (is it the same, or different?)
* forms: series_title_volume, schema: NA
* forms: publication_status_language.language, schema: there are language, publication_status and status fields - which one fits this field?
* forms: publication_status_language.publication_status, schema: see previous
* forms: locked, schema: NA

I did not list all, just some of the first examples. Again: I might basically misinterpret it.

**Comment by phochste** [comment]
Yes as I said, the JSON schema is still incomplete. It is an exercise to check if all the possible fields are really in the catmandu.schema.yml (as should be).

**Comment by nicolasfranck** [comment]
Indeed, I tried to derive a schema from the examples. Because I'm not the creator of the examples, this should be validated by those who created the examples..

**Comment by phochste** [comment]
I'm creating a script to generate the Markdown schema from the catmandu.schemas.yml configuration file itself:

     ./bin/schema2markdown.pl

This will be easier to keep the documentation up to date. I'm now transferring all your human descriptions into the configuration file.

**Comment by petrakohorst** [comment]
@pkiraly Let me try to explain some these fields:

> forms: series_title_volume, schema: NA
> forms: publication_status_language.language, schema: there are language, publication_status and status fields - which one fits this field?

These are combination fields (publication_status and language combined into one line in the input form; series_title and volume combined into one line in the input form) that exist in the forms.yml in this way, because the template generator uses the forms.yml (and the names used therein) to choose which template to put into a form. So, in order to get the fields series_title and volume in one row into the form, I had to put them into the same template and name it series_title_volume.tt

For the schema and validation these fields should be viewed separately. volume has its own validation and series_title has its own validation and schema. The same goes for publication_status and language.

> forms: locked, schema: NA

Locked is a 1|0 field that only determines whether the whole record can be edited (by anyone but admins) or not.

> forms: year_extern, schema: year (is it the same, or different?)

year_extern.tt is another combination template: year is indeed the standard year field (and should abide by its schema and validaton) and extern is a checkbox indicating whether the record was created while employed at our university or before (or after) that time. Again, year and the "extern" checkbox go into one line in the input form and thus needed to be in the same template.

***Mind you, I'm planning to do a huge refactoring of the template generator which will (hopefully) get rid of all of these quick-and-dirty solutions that now mess up our schemas, yml- and template-files. Sorry for all the confusion!***

> An inconsistency: researcher's external_id.isi has a constraints ("^[0-9]+$"), while isi doesn't have.

Researcher doesn't have external_id. Where did you see this?
There are two different fields in publication: "external_id.isi" and "isi". "external_id.isi" is the actual input field in the form and should be in the schema. "isi" is just a check (at indexing time) whether there is an isi identifier in the record or not. It's a 1|0 field that's added via fix so we can search for all records with isi=1 - all records that have an isi identifier.

---
I am currently working on some full examples and then on an update to the schemas.yml or some other way of completing this documentation.

**Comment by phochste** [comment]
I've updated the complete documentation for the JSON schema and documentation and created a 'bin/librecat schemas' command line tool to inspect the schemas. All that is rest is debugging and filling in the '???'-s.
