### ISSUE TITLE
DOI and ISBN registration

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#284]
Ref. Wageningen's services http://elag2017.org/?option=com_sppagebuilder&view=page&id=46

**Comment by vpeil** [comment]
DOI registration is supported via `LibreCat::Worker::DataCite` and the hook `LibreCat::Hook::new_research_data_datacite` (maybe choose a better name, sth. `...register`), but has been applied to type=research_data only.

We could hook that in whereever we want (also in layer!), or think about a checkbox in edit forms 
like ("Give me a DOI :white_check_mark: )

ISBN registry looks weird. Can't see any API or documenation and it depends on the country???
e.g. http://www.german-isbn.de/

**Comment by vpeil** [comment]
A solution for the DOI registration is available on branch [doi_register](https://github.com/LibreCat/LibreCat/tree/pr/doi_register)
I think this branch needs a bit of testing, then this will be suggested as a PR.

I have written a small documentation: https://github.com/LibreCat/LibreCat/wiki/DOI-Registration

Please let me know, if something is missing.

**Comment by patrickda** [comment]
For the ISBN an institution can by a package with a distinguished prefix and i think the llast number has to be calculated. 
We would be also interested in the feature for our thesis. 
Give me a few days and I will provide more information about the ISBN.

**Comment by vpeil** [comment]
@patrickda you mean that **one does not have to** push data anywhere? That would make things very easy.
Yes, the last digit is a checksum, all you need as provided by the perl module [Business::ISBN](https://metacpan.org/pod/Business::ISBN)

**Comment by patrickda** [comment]
As far as i know,  this is not necessary. We got a block of ISBNs (the block is defined by the third number sequence, the second is the country. the fourth block can be just a number which is counting up. Therefor it just must be possible anywhere to define the registered block, so that a new ISBN can be created from the block ([see also Wikipedia](https://en.wikipedia.org/wiki/International_Standard_Book_Number#How_ISBNs_are_issued)) also an automated information if the block runs out would be cool. At last we would only use this feature for a specific item type (thesis).  

Still the whole item (book /ebook) has to send to the national library for documentation.

**Comment by vpeil** [comment]
Sending stuff to a national library is up to local implementations, I guess. You would do this via `LibreCat::Hook`s.

**Comment by vpeil** [comment]
I think this is done since the merged of PR #493 .

For ISBNs, either see discussion above or open a new ticket. But then, one has to provide some information.
