### ISSUE TITLE
Insight from user tracking

### ISSUE THREAD

**Issue by nilswindisch** [LibreCat/LibreCat#29]
Related to the question of how to provide the best possible user experience:

Has anyone used user tracking on LibreCat sites in the past and can give me some insights like what typical and/or frequent user flows are and what features are most used?

**Comment by phochste** [comment]
I don't think user tracking is allowed in Germany. At Ghent we use Google Analytics for our http://biblio.ugent.be.

The most frequent used pages are those that are indexed via Google (Scholar) ..which means all the author and publication pages.

 * Publication details page ~ 18% page views
 * Person detail page ~ 17% page views
 * Search box (publications) +/- 15% of the page views

In comparison, the homepage only gets 2% of the page views, catalogging records about 13%.

85% of the clients are desktop
11% of the clients use a mobile device
3% of the clients use a tablet

46% Chrome
17% Firefox
16% Safari
15% Internet Explorer
3% Edge

Currently we have an average page load time of 2.6 seconds and 0.36 for a server response time.

If you need more information, just ping me.

**Comment by pietsch** [comment]
At Bielefeld University Library, we do not use trackers. However, we do analyse anonymised logfiles. Initiatlly we used Piwik (without any trackers) for this, but Piwik's logfile importer is a contributed, unsupported Python script that basically stopped working after some Piwik upgrade. So we switched to AWstats for analyzing logfiles. In contrast to Piwik, AWstats does not have a built-in logfile anonymiser. In order to use it in a law-conforming way, I wrote a little [logfile anonymiser in Perl](/pietsch/loganalyse).

@phochste You might want to double-check if pertinent EU law applies in Belgium.

@nilswindisch Do you need figures like the ones Patrick provided?

**Comment by nilswindisch** [comment]
Thank you very much and sorry about my belated answer.

These kind of stats are very helpful.

@pietsch Numbers from Bielefeld are highly appreciated.

We plan on using Piwik from the start. We might not do AB-tests, but will evaluate more than /just/ access; things like "this link was visible n times but user interacted only x times with it".

User tracking is allowed as long as we anonymize part of the IP and give user notice about tracking and the option to opt out. Even Google Analytics is fine in Germany, but not at the University Göttingen.

@phochste we plan on supporting browsers with a market share of >5%, maybe your numbers can support that?

**Comment by phochste** [comment]
I also manage other websites and the list of >5% browsers isn't different from what given here. The 11% mobile traffic is a bit higher than on other (project) websites.

**Comment by vpeil** [comment]
@nilswindisch can this one be closed? do you need more input?
