### ISSUE TITLE
Editing of uploaded BibTex records gives internal error

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#324]
- Go to 'Add new publication'
- Paste this BibText:

```
@article{small,
author = {Freely, I.P.},
title = {A small paper},
journal = {The journal of small papers},
year = 1997,
volume = {-1},
note = {to appear},
}

@article{big,
author = {Jass, Hugh},
title = {A big paper},
journal = {The journal of big papers},
year = 7991,
volume = {MCMXCVII},
}
```

- Click import 
- Click on any of the two new 'Edit' links and get an internal error

**Comment by phochste** [comment]
Also the uploaded BibTex records don't have the same order as show above

**Comment by nicolasfranck** [comment]
cf. https://github.com/LibreCat/LibreCat/pull/338

Fixes a typo, which now leads in LibreCat (correctly) to a http status code 403.
Front end test will work after merge of pull request:

https://github.com/LibreCat/LibreCat-Frontend-Tests/pull/6

Reason: the publication is not yet indexed (the "wait" problem), and the method "can_edit" determines access by
constructing a cql query to the index, instead of retrieving the publication record from the database and compare it against that.

So: use the publication record from the database to determine rights?

**Comment by phochste** [comment]
There was still code left in the BiBTeX importer code that didn't store the records both in the main store and in the search index. I thought I had reverted all attempts to handle indexation in hooks. This bug is now fixed in `dev`. 

@verheyenkoen  you can merge in frontend-tests

**Comment by verheyenkoen** [comment]
Test merged.
