### ISSUE TITLE
Export marked publications not in right order

### ISSUE THREAD

**Issue by verheyenkoen** [LibreCat/LibreCat#326]
Scenario:

* Open a couple of publications and mark them
* Go to the marked publications page
* Reorder the publications
* Export in any format (tested with BibTeX, JSON and YAML)
* The publications are not ordered accordingly in the export. They always seem to be in the ordered as on the publications page (recent first?).

**Comment by verheyenkoen** [comment]
Added test for this in branch [issues/326](https://github.com/LibreCat/LibreCat-Frontend-Tests/tree/issues/326). Can be merged in master when issue is fixed.

To run test:
```
$ $(npm bin)/cypress run --spec cypress/integration/issues/issue-326.spec.js
```

**Comment by nicolasfranck** [comment]
The question is: can we actually support this?

* The page "/marked" uses the identifiers from the array session("marked"), and fetches the records one after the other from the index. So the order is always correct. This is done "add hoc".

* The page /marked.:fmt forwards the request to a general route /export where these parameters are supported:

    * format
    * cql
    * sort
    * style
    * links
    * bag

So the route /marked.:fmt choose to just "join" the identifiers into an cql query, but in that way the order is not preserved. 

So either we drop functionality like "reorder", so that the order of the output does not matter,
or we add a parameter like "ids" to the route "/export" that overrides both "cql" and "sort".

**Comment by vpeil** [comment]
@nicolasfranck thanks for your analysis! As for me, I am friend of clean and simple functionality and code. I am voting for remove **reorder functionality**.

What do others think?

**Comment by nicolasfranck** [comment]
Well, at least, we cannot mix up two different things:

* export based on a query (sort determined by index or "sort by")
* export based on a list of identifiers (sort determined by the user's selection, so the last selected at the end?)

In each case there is an order applied to the records.

A lot of functionality is done in the route "/export". So I think
it is better to port part of the functionality to a list of helper functions so
those parts can be reused. That way no "special" parameters (like "ids") need
to be added to the route "/export":

* extract parameters and create "handling package"
* determined appropriate content type

In that way the two routes can decide how to fetch the records.

P.S. What is the use case for this  basket functionality?

**Comment by vpeil** [comment]
> P.S. What is the use case for this basket functionality?
Isnt't it a standard in all "digital libraries", marking and exporting? Our use is the following: some funding proposals need to include the authors 5 most relevant publications (and **not all** the authors publication).

... and the biblio frontend has this functionality, too :smile:
