### ISSUE TITLE
Add support (automatic) registration of users

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#39]
Currently in LibreCat, a user needs to be registered in the researchers database to get a working login (via LDAP or any other method). This is not feasible in an institute like Ghent, where we can't have an administrative workflow to register users.
1. Create a page where authenticated LDAP users can register themselves.
2. Possible make this registration automatic (with as less administrative fuss as possible).

**Comment by nicolasfranck** [comment]
Possibly we should offer two options:

1. autocreate + filter: create user record when it does not exist. Maybe offer the possibility to refuse when certain (ldap?) attributes are not correct.
2. activation: 
   2.1. an administrator gets a notification about a new user, and activates the user.
   2.2. OR: the user gets a verification email

The filter should be optional. We should find a way to register "callbacks" (from a configuration point),
instead of relying on "this attribute equals that".

The activation should be required, wether or not an administrator should step in.

**Comment by phochste** [comment]
I don't know a use-case why the activation should be a require feature? A successful LDAP authentication is a pretty strong verification you are the 'real' person. Much better than on the standard social networks where it it pretty easy to claim  you are "Mr X" (just create a account where the name isn't in use yet). This is not the case for LDAP logins. True it is the case for 'external' non-LDAP users.

**Comment by nicolasfranck** [comment]
right ;-) I was confusing this with internal accounts where activation is often used.

1. autocreate when single-sign-on is used (could be ldap, orcid ..)

**Comment by vpeil** [comment]
yes, would be very useful.

**Comment by vpeil** [comment]
Auto-Registration can be achieved with with class `LibreCat::Auth::SSO`, e.g.

copy `LibeCat::Auth::SSO::Simple` to your local layer and modify it to your needs (check if user exists and if not create an user account).
