### ISSUE TITLE
Testing new citation styles with livecitation

### ISSUE THREAD

**Issue by feldi88** [LibreCat/LibreCat#424]
The wiki describes a way to test new styles with the livecitation route (see https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language#using-librecat-to-test). It sounds that it is possible to test new citation styles which have not been configured in the current LibreCat installation. (Especially, because this feature does not make so much sense for already configured styles since you can look up the output at the publication page.)

Sadly, it only works for already configured styles: The LiveCitation route uses the Citation class with the given style as parameter. And the Citation then looks up with this parameter a configured style name:
https://github.com/LibreCat/LibreCat/blob/92e7eac8a1fc2fda558524d6bfc1068bdf2d4b99/lib/LibreCat/Citation.pm#L128

What is the "true" idea behind the LiveCitation feature?

**Comment by petrakohorst** [comment]
The idea behind the livecitation route is to test changes in csl style files directly. I'm not sure about the current implementation, but in our local system we still save citations directly in the record as text, so that rendering a frontdoor or publication list is quick and painless. We do not display citations "on-the-fly" directly from the csl engine.

To test changes in a csl style file, I would need to edit and save an existing record so that the changed citation gets rendered, check the change and correct it if necessary. This is quite time consuming and unnecessary. Also, in the meantime a user might have updated a record and my faulty change ends up in their record. Not good!
(Note: So far we did not have a running csl engine on a dev system! Our csl engine always only worked on our live system.)

So the livecitation feature is meant to be a direct access to the csl engine where you can change a copy of any style file and view the rendered changes directly (even if the name of the copied style file is not in the config's list of styles -> that was the main reason for livecitation). All the while the styles for the running system remain safe and untouched because the config only allows tested and approved styles to be stored in actual records.

It seems that in the current version of the code the livecitation feature uses the config, even though it shouldn't.
