### ISSUE TITLE
"Search similar" should not change title to search

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#500]
In views/links.tt, the title to be searched is filtered:

```
<a href='[% uri_base %]/librecat/search/admin/similar_search?q="[% entry.title.replace("[\'\"\,\;\:\.]+","") %]"'>[% h.loc("main_page.links.search_similar") %]</a>
```

that's a job for ElasticSearch. This should be sufficient:

```
<a href='[% uri_base %]/librecat/search/admin/similar_search?q="[% entry.title | uri %]"'>[% h.loc("main_page.links.search_similar") %]</a>
```

I found this problem because I'm using file names as titles, and e.g. "input.jpeg" was changed to "inputjpeg", which could not be found.

See: https://github.com/LibreCat/LibreCat/blob/dev/views/links.tt#L68

**Comment by vpeil** [comment]
Even if it would be necessary, it should not be contained in the templates.

**Comment by nicolasfranck** [comment]
by the way, why is this route necessary? One could simply create a link to current search page with the parameter "q" filled. I see that this route similar_search creates a special query to match less accurate on titles, but shouldn't that be done in the main search page /admin/librecat (where there is also a filter on the deleted records!). Maybe set the accuracy on the field "title"?

Image someone just accessing the page "/admin/search", typing in a title, and expecting to find all titles that look like his/her query. Now you first need to find a specific record, and then this functionality is available.

**Comment by petrakohorst** [comment]
```[% entry.title | uri %]``` looks good, but it is not sufficient. It doesn't solve the problem with the title "input.jpeg". Even with the uri filter, the title "input jpeg" is not found when searching for "input.jpeg". To solve this we should rather consider replacing punctuation with whitespace instead of nothing. But then only one direction will work. Searching for "input.jpeg" will find "input jpeg" but not the other way around. It remains a problem.

Also: without the replace and with only the uri filter, titles with single quotes will be cut off (due to the template quotes). So, at least single and double quotes need to be removed here.

Unfortunately this replacement needs to be done in the template, because of the single/double quote problem mentioned above. It does not suffice to replace or remove these characters later on in the route. Because the whole search term doesn't even make it to the route in the first place.

Example:

```Full publication 'journal article': the first one``` will be cut off in the template after the word publication and the following space.

As for the idea of using the parameter q and the regular search: in general I agree, that would be better. But I don't see how one would integrate the native search with match percentages into the regular search.

The similar search was meant for duplicate control/check, done by our support team, not so much for browsing.

**Very good point about the deleted records filter, though!** I had not realized that this search also returns delted records. I have added this filter to the search query and will submit a PR.

**Comment by nicolasfranck** [comment]
@petrakohorst : well you need a few things

* title through filter URI. Or just construct the url using h.uri_for (or the internal dancer uri_for) that also takes care of the escaping

```
[% h.uri_for( "/librecat/search/admin/similar_search", q = entry.title) %]
```
* when you put the url inside a html attribute, you need to apply the HTML filter:

```
<a href="[% h.uri_for( '/librecat/search/admin/similar_search', q = entry.title) | html %]">search</a>
```

* if "input.jpeg" cannot be found, than it means that the field analysis in elasticsearch should be changed (split on "." which is not done by the standard analyzer. You can do this in a char filter before the tokenization for example). This way the search is fixed not just for this specific case.

That's common practice ;-)

Concerning the "similar search" route: well yes, CQL is probably too limited to translate to something like "70% should match". 

Something else: once you're on the page "similar search" you're stuck in this page. Every search query does not go back to the regular page.
