### ISSUE TITLE
download links should contain less information

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#501]
Every download link now contains both the file_id and the file_name of the file.
But only the file_id is taken into account:

e.g. http://demo.librecat.org/download/58/60/Moelders%20Schrape%202017%20%E2%80%93%20Neue%20Irritationspotentiale%20in%20der%20digitalen%20Gesellschaft%20(Preprint).pdf

Shouldn't that be?

http://demo.librecat.org/download/58/60

which works also

That would make the controller much simpler to write:

```
get "/download/:id/:file_id" => sub {
```

instead of:
```
get qr{/download/([0-9A-F-]+)/([0-9A-F-]+).*} => sub {
```

**Comment by nicolasfranck** [comment]
BTW: if your "file_id" is something else than a number of hexadecimal number, the the link doesn't work. e.g. file_id = "MA"

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/pull/503

**Comment by phochste** [comment]
Download links with a file extension are exposed to make search engines as Google Scholar happy.  They need to heuristics to guess if a repository contains full-text or not. There are no global specs how to do this. What they do now is guess by the file extension that a record with a link to a ".pdf" (or whatever binary format) must be some kind of full text link.

**Comment by feldi-online** [comment]
To support @phochste I would vote for file extensions. But I find it a little bit unlucky, that the download link contains the whole original file name of the author since they could include private information or they do not look nice and consistent in general.

Another solution (which is used quite often in web applications) would be the following scheme:

`/download/<pub_id>/<file_id>.<extension>`

For example: `/download/2344325/2443242.pdf`

If there is only one main document, it would even be nice to have a link like `/download/<pub_id>.<extensions>` but I think that is not implementable because of the possibility to have mulitple files for each publication.

**Comment by nicolasfranck** [comment]
See other pull request now: https://github.com/LibreCat/LibreCat/pull/525
