### ISSUE TITLE
Abstract is not saved when no language is selected

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#506]
- Fill in an abstract but don't set a language
- Save the record
- The abstract is not saved in the database

**Comment by petrakohorst** [comment]
Yes, this was intentional behavior. Same as, for example, the author field being deleted if it only consists of a first name but no last name.

We need a language for an abstract, since you can add several abstracts in different languages.

A solution would be to automatically set the language to english if no language is specified.

**Comment by phochste** [comment]
IMO, this is a wrong intention. End users shouldn't guess which data will be stored or not. They spend their time typing an abstract, at least there should be a warning this field will be deleted.

Automatic setting a language would be a good solution

**Comment by petrakohorst** [comment]
I agree that the current behavior in the core makes no sense (for the user) whatsoever.

I checked our live system to see where this came from:
1. Our live system presets the abstract language to english, so that the user cannot forget to set a language.
2. There is no "--select--" option in our language select box.
3. There is a "-- other --" entry in the language select box for anyone not wanting to select a specific language. But that entry still has a value behind it (some number or ID) and thus gets stored.

On the demo server/ in the LibreCat core this is different.

Should I copy the behavior from our live system to the core and make a PR?

**Comment by phochste** [comment]
@petrakohorst Yes that would also be a good solution

**Comment by vpeil** [comment]
solution is available, see PR #508
