### ISSUE TITLE
Journal Article - citation default: No full page range

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#566]
Should be page 159–172

![ris-journal-article-page-range](https://user-images.githubusercontent.com/30523869/44567556-3f4eb300-a773-11e8-9c12-bcb003929876.PNG)

**Comment by vpeil** [comment]
@petrakohorst is this related to PR #538

**Comment by petrakohorst** [comment]
It could be related to the PR, but in the case of the PR, the page numbers didn't get stored in the record at all.

@datango could you please check, if the page range gets stored correctly? (Internal view or check directly in the index)

If the page range gets stored in the rec correctly, but shows up wrong in the citation, it's a citation fix problem.  
If the page range gets stored incorreclty, it might be related to PR #538

**Comment by datango** [comment]
intvolume: '        15'
issue: '1'
page: 159–172
publication: Zeithistorische Forschungen / Studies in Contemporary History
status: public
title: Graffiti digital. Das Informationssystem Graffiti in Deutschland (INGRID)
type: journal_article
user_id: '12548'
volume: 15
year: '2018'
...

**Comment by petrakohorst** [comment]
Okay, I see. There appears to be an mdash between the page numbers instead of a regular dash.

Please edit the record, remove the existing dash and type it in again, then save the rec. That should work.

The to_csl fix matches normal dashes in the page field but not mdash or ndash (which usually only get into the data if users copy text from webpages or pdf documents).

**Comment by datango** [comment]
I have change the – to -

intvolume: '        15'
issue: '1'
page: 159-172
publication: Zeithistorische Forschungen / Studies in Contemporary History
status: public
title: Graffiti digital. Das Informationssystem Graffiti in Deutschland (INGRID)
type: journal_article
user_id: '1112'
volume: 15

Still the incorrect output:

![grafik](https://user-images.githubusercontent.com/30523869/44784828-2c7f1880-ab8f-11e8-815c-bef968f152a4.png)

**Comment by vpeil** [comment]
What is your default citation style? The problem could be the style itself.

**Comment by petrakohorst** [comment]
...or that the citation doesn't get updated at all.  
Please try changing the field publication slightly, so that you can see if changes actually make it to the citation.

And if changes do make it into the citation and the problem still persists: please paste the lines from the csl fix file that concern the field "page".

**Comment by datango** [comment]
default_style: short

Updates in title field are updated correctly.

![grafik](https://user-images.githubusercontent.com/30523869/44832322-b7f9b780-ac2a-11e8-92ed-c8868eba3cee.png)

![grafik](https://user-images.githubusercontent.com/30523869/44832348-d2339580-ac2a-11e8-960f-2730bccc3674.png)

Looks like the style short has this problem.

**Comment by vpeil** [comment]
This has been fixed in 5855c33, and released with v1.2.1
