### ISSUE TITLE
cpanfile dependencies, specific version?

### ISSUE THREAD

**Issue by ArSa-Apps** [LibreCat/LibreCat#61]
Hi,
currently I replace all the "**==**" in `cpanfile` with "**>=**" since some versions of the modules are not available anymore and been replaced with newer ones. Should this change be permanent in the original file or does it raise any problems?
Cheers,
A.

**Comment by phochste** [comment]
If there is a `==` in the `cpan` file it means very explicitly that this particular version is required and not something else. The `>=` means that all previous versions of this module will not work with the code.

When changing the `==` to `>=` this means you have installed the newest versions and are certain that this code will work.

Only two modules have an `==` in the cpan file:

    requires 'Search::Elasticsearch', '==1.19';
    requires 'MIME::Types','==1.38';

ElasticSearch is because of the requirement of ElasticSearch 1.X in Librecat. 
The MIME::Type  because of an bug in 1.29 MIME::Type (see https://github.com/LibreCat/LibreCat/issues/3)  I don't know if this has been solved yet.

**Comment by vpeil** [comment]
@ArSa-Apps do you still have issues with the cpanfile? I wouldn't change because it's tested and well working for us...

**Comment by ArSa-Apps** [comment]
No, it worked find after I set the **PERLIB5** and only used `carton install`.
