### ISSUE TITLE
Back link /broken/ when user enters publication page directly

### ISSUE THREAD

**Issue by nilswindisch** [LibreCat/LibreCat#65]
As seen here: https://pub.uni-bielefeld.de/data/2698627 the back link does nothing, because it uses js history - which is empty when users follows an external link to a LibreCat publications page.

<img width="1102" alt="screenshot 2016-09-27 08 38 00" src="https://cloud.githubusercontent.com/assets/914680/18862699/fc699712-848d-11e6-9bcd-9cc23fec38b1.png">

**Comment by vpeil** [comment]
@nilswindisch any advise how to solve this? Or we shouldn't use back links at all?

**Comment by nilswindisch** [comment]
imho back links are obsolete within the website UI, because "back" is a native browser feature. For the göttingen layer I will not show any back buttons at all. If there are required for any reason, you may check the history and "if empty" = "display: none".
side note: it's a feature that doesn't work with javascript switched off, so there should be a check if js is active already.

**Comment by nilswindisch** [comment]
@vpeil can you work with my answer or can I be helpful in a different way? just let me know.

**Comment by vpeil** [comment]
well... for the simple solution: for the librecat core (i.e. this repository) I have just deleted the back button and the whole breadcrumb stuff, since the login information is already available in the topbar.

For the Bielefeld case, I tried to fix this, but this discussion here didn't help much
http://stackoverflow.com/questions/3588315/how-to-check-if-the-user-can-go-back-in-browser-history-or-not

Just deleting this unnecessary feature would be easier

**Comment by nilswindisch** [comment]
Ah, I see. After glimpsing into the stackoverflow thread I'm even more for removing it ;)

**Comment by vpeil** [comment]
deleted! thanks for pointing us to this problem!
