### ISSUE TITLE
Nameless Authors

### ISSUE THREAD

**Issue by nilswindisch** [LibreCat/LibreCat#70]
<img width="319" alt="screen shot 2016-10-11 at 15 06 03" src="https://cloud.githubusercontent.com/assets/914680/19271282/4bc91e4a-8fc4-11e6-8775-4c3097c3bf89.png">

**Comment by petrakohorst** [comment]
This is not a bug but a "problem" with the initially imported records. In one of those records, two authors have UniBi ids and thus get indexed by elasticsearch and returned by the author facet. They are not in the researcher index, though. So they cannot be displayed with name according to their id (since no id/name/record of them exists).
I removed the ids from that record and now the authors filter is gone altogether (as it should be). If someone connects an existing author from the researcher index with a record, the filter will show up correctly.

**Comment by nilswindisch** [comment]
Ah, didn't know that. For Göttingen is implemented a fallback where the ID is visible if no name available.
